auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

common:
  # общая директория для всех компонентов
  path_prefix: /loki
  # ring + репликация для одного узла
  ring:
    kvstore:
      store: inmemory
  replication_factor: 1

schema_config:
  configs:
    - from: "2023-01-01"
      # в локальном режиме для индекса shipper: boltdb-shipper или tsdb
      store: tsdb                 # ← или boltdb-shipper
      object_store: filesystem    # FS для хранения промежуточных таблиц индекса
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks     # директория для чанков