global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # ─── сам Prometheus ───
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # ─── метрики хоста ───
  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']

  # ─── метрики всех Docker-контейнеров через cAdvisor ───
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  # ─── (опц.) любой сервис, который сам отдаёт /metrics ───
  #     пример: FastAPI app с prometheus-client
  - job_name: goats-service
    static_configs:
      - targets: ['goats-service:8000']
        labels:
          app: goats

  # ─── (опц.) авто-дискавери обычных контейнеров ───
  #     убери, если не нужно или докер-сокет не монтируешь
  # - job_name: docker-containers
  #   docker_sd_configs:
  #     - host: unix:///var/run/docker.sock
  #       refresh_interval: 1m
  #   relabel_configs:
  #     - source_labels: [__meta_docker_container_name]
  #       regex: '/(.*)'
  #       target_label: container