global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker-containers'
    metrics_path: /metrics
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      - source_labels: [__meta_dockerswarm_service_name]
        regex: .+
        action: keep

  - job_name: 'varlogs'
    static_configs:
      - targets: ['localhost']
        labels:
          job: 'varlogs'